services:
  - type: web
    name: fyers-volume-spike-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: TZ
        value: Asia/Kolkata
    buildFilter:
      paths:
        - requirements.txt
        - main.py
        - "*.py"
    routes:
      - type: rewrite
        source: /
        destination: /
